spring:
  application:
    name: LicensingService
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8888/configserver/
  cloud:
   config:
    enabled: true
    eureka:
     instance:
      preferIpAddress: true
    client:
     registerWithEureka: true
     fetchRegistry: true
     serviceUrl:
      defaultZone: http://localhost:8761/eureka/
example.property: hello
management:
  endpoint:
    metrics:
      enabled: true
    loggers:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'