server:
  port: 8008
spring:
  application:
    name: LicensingService
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8888/configserver/
  cloud:
   config:
    enabled: true
    eureka:
     instance:
      preferIpAddress: true
    client:
     registerWithEureka: true
     fetchRegistry: true
     serviceUrl:
      defaultZone: http://localhost:8761/eureka/
example.property: hello

resilience4j:
 circuitbreaker:
  instances:
    getLicensesByOrg:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
 retry:
   instances:
     getLicensesByOrg:
       registerHealthIndicator: true
       maxRetryAttempts: 3
       waitDuration: 5s
 rateLimiter:
   instances:
     getLicensesByOrg:
       registerHealthIndicator: true
       limitForPeriod: 10
       limitRefreshPeriod: 10s
       timeoutDuration: 10s
management:
  endpoint:
    metrics:
      enabled: true
    loggers:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'