spring:
  config:
    import: configserver:http://localhost:8888/licensingservice/
example.property: hello
management:
  endpoint:
    metrics:
      enabled: true
    loggers:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'